# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lidar_form.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LidarForm(object):
    def setupUi(self, LidarForm):
        LidarForm.setObjectName("LidarForm")
        LidarForm.resize(754, 506)
        self.centralwidget = QtWidgets.QWidget(LidarForm)
        self.centralwidget.setGeometry(QtCore.QRect(4, 11, 746, 491))
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(150, 450, 461, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.doubleSpinBox_horizontal_fov = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_horizontal_fov.setGeometry(QtCore.QRect(190, 130, 80, 25))
        self.doubleSpinBox_horizontal_fov.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_horizontal_fov.setMinimum(-180.0)
        self.doubleSpinBox_horizontal_fov.setMaximum(180.0)
        self.doubleSpinBox_horizontal_fov.setSingleStep(0.1)
        self.doubleSpinBox_horizontal_fov.setProperty("value", 120.0)
        self.doubleSpinBox_horizontal_fov.setObjectName("doubleSpinBox_horizontal_fov")
        self.lineEdit_name = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_name.setGeometry(QtCore.QRect(40, 65, 250, 26))
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.label_horizontal_fov = QtWidgets.QLabel(self.centralwidget)
        self.label_horizontal_fov.setGeometry(QtCore.QRect(50, 130, 110, 25))
        self.label_horizontal_fov.setObjectName("label_horizontal_fov")
        self.label_vertical_fov = QtWidgets.QLabel(self.centralwidget)
        self.label_vertical_fov.setGeometry(QtCore.QRect(70, 160, 100, 25))
        self.label_vertical_fov.setObjectName("label_vertical_fov")
        self.label_horizontal_resolution = QtWidgets.QLabel(self.centralwidget)
        self.label_horizontal_resolution.setGeometry(QtCore.QRect(20, 190, 150, 25))
        self.label_horizontal_resolution.setObjectName("label_horizontal_resolution")
        self.label_vertical_resolution = QtWidgets.QLabel(self.centralwidget)
        self.label_vertical_resolution.setGeometry(QtCore.QRect(30, 220, 140, 25))
        self.label_vertical_resolution.setObjectName("label_vertical_resolution")
        self.label_max_range = QtWidgets.QLabel(self.centralwidget)
        self.label_max_range.setGeometry(QtCore.QRect(30, 250, 140, 20))
        self.label_max_range.setObjectName("label_max_range")
        self.label_min_range = QtWidgets.QLabel(self.centralwidget)
        self.label_min_range.setGeometry(QtCore.QRect(30, 280, 140, 25))
        self.label_min_range.setObjectName("label_min_range")
        self.doubleSpinBox_vertical_fov = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_vertical_fov.setGeometry(QtCore.QRect(190, 160, 80, 25))
        self.doubleSpinBox_vertical_fov.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_vertical_fov.setMinimum(-180.0)
        self.doubleSpinBox_vertical_fov.setMaximum(180.0)
        self.doubleSpinBox_vertical_fov.setSingleStep(0.1)
        self.doubleSpinBox_vertical_fov.setProperty("value", 32.0)
        self.doubleSpinBox_vertical_fov.setObjectName("doubleSpinBox_vertical_fov")
        self.doubleSpinBox_horizontal_resolution = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_horizontal_resolution.setGeometry(QtCore.QRect(190, 190, 80, 25))
        self.doubleSpinBox_horizontal_resolution.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_horizontal_resolution.setDecimals(3)
        self.doubleSpinBox_horizontal_resolution.setMinimum(0.05)
        self.doubleSpinBox_horizontal_resolution.setMaximum(180.0)
        self.doubleSpinBox_horizontal_resolution.setSingleStep(0.1)
        self.doubleSpinBox_horizontal_resolution.setProperty("value", 0.25)
        self.doubleSpinBox_horizontal_resolution.setObjectName("doubleSpinBox_horizontal_resolution")
        self.doubleSpinBox_vertical_resolution = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_vertical_resolution.setGeometry(QtCore.QRect(190, 220, 80, 25))
        self.doubleSpinBox_vertical_resolution.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_vertical_resolution.setDecimals(3)
        self.doubleSpinBox_vertical_resolution.setMinimum(0.05)
        self.doubleSpinBox_vertical_resolution.setMaximum(180.0)
        self.doubleSpinBox_vertical_resolution.setSingleStep(0.1)
        self.doubleSpinBox_vertical_resolution.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.doubleSpinBox_vertical_resolution.setProperty("value", 0.25)
        self.doubleSpinBox_vertical_resolution.setObjectName("doubleSpinBox_vertical_resolution")
        self.doubleSpinBox_max_range = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_max_range.setGeometry(QtCore.QRect(190, 250, 80, 25))
        self.doubleSpinBox_max_range.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_max_range.setMaximum(1000.0)
        self.doubleSpinBox_max_range.setSingleStep(0.1)
        self.doubleSpinBox_max_range.setProperty("value", 30.0)
        self.doubleSpinBox_max_range.setObjectName("doubleSpinBox_max_range")
        self.doubleSpinBox_min_range = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_min_range.setGeometry(QtCore.QRect(190, 280, 80, 25))
        self.doubleSpinBox_min_range.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_min_range.setMaximum(1000.0)
        self.doubleSpinBox_min_range.setSingleStep(0.1)
        self.doubleSpinBox_min_range.setObjectName("doubleSpinBox_min_range")
        self.doubleSpinBox_mounting_x = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_mounting_x.setGeometry(QtCore.QRect(390, 130, 80, 25))
        self.doubleSpinBox_mounting_x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_mounting_x.setMinimum(-10.0)
        self.doubleSpinBox_mounting_x.setMaximum(10.0)
        self.doubleSpinBox_mounting_x.setSingleStep(0.1)
        self.doubleSpinBox_mounting_x.setObjectName("doubleSpinBox_mounting_x")
        self.doubleSpinBox_mounting_y = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_mounting_y.setGeometry(QtCore.QRect(390, 160, 80, 25))
        self.doubleSpinBox_mounting_y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_mounting_y.setMinimum(-10.0)
        self.doubleSpinBox_mounting_y.setMaximum(10.0)
        self.doubleSpinBox_mounting_y.setSingleStep(0.1)
        self.doubleSpinBox_mounting_y.setObjectName("doubleSpinBox_mounting_y")
        self.lineEdit_frame = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_frame.setGeometry(QtCore.QRect(490, 65, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_frame.setFont(font)
        self.lineEdit_frame.setObjectName("lineEdit_frame")
        self.label_mounting_x = QtWidgets.QLabel(self.centralwidget)
        self.label_mounting_x.setGeometry(QtCore.QRect(345, 130, 40, 25))
        self.label_mounting_x.setAlignment(QtCore.Qt.AlignCenter)
        self.label_mounting_x.setObjectName("label_mounting_x")
        self.label_mounting_y = QtWidgets.QLabel(self.centralwidget)
        self.label_mounting_y.setGeometry(QtCore.QRect(345, 160, 40, 25))
        self.label_mounting_y.setMouseTracking(False)
        self.label_mounting_y.setAlignment(QtCore.Qt.AlignCenter)
        self.label_mounting_y.setObjectName("label_mounting_y")
        self.label_mounting_z = QtWidgets.QLabel(self.centralwidget)
        self.label_mounting_z.setGeometry(QtCore.QRect(345, 190, 40, 25))
        self.label_mounting_z.setAlignment(QtCore.Qt.AlignCenter)
        self.label_mounting_z.setObjectName("label_mounting_z")
        self.label_mounting_roll = QtWidgets.QLabel(self.centralwidget)
        self.label_mounting_roll.setGeometry(QtCore.QRect(340, 240, 60, 25))
        self.label_mounting_roll.setAlignment(QtCore.Qt.AlignCenter)
        self.label_mounting_roll.setObjectName("label_mounting_roll")
        self.label_mounting_pitch = QtWidgets.QLabel(self.centralwidget)
        self.label_mounting_pitch.setGeometry(QtCore.QRect(480, 240, 70, 25))
        self.label_mounting_pitch.setObjectName("label_mounting_pitch")
        self.label_mounting_yaw = QtWidgets.QLabel(self.centralwidget)
        self.label_mounting_yaw.setGeometry(QtCore.QRect(610, 240, 60, 25))
        self.label_mounting_yaw.setObjectName("label_mounting_yaw")
        self.label_frequency = QtWidgets.QLabel(self.centralwidget)
        self.label_frequency.setGeometry(QtCore.QRect(40, 310, 130, 25))
        self.label_frequency.setObjectName("label_frequency")
        self.doubleSpinBox_frequency = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_frequency.setGeometry(QtCore.QRect(190, 310, 80, 25))
        self.doubleSpinBox_frequency.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_frequency.setMinimum(0.01)
        self.doubleSpinBox_frequency.setMaximum(1000.0)
        self.doubleSpinBox_frequency.setSingleStep(0.1)
        self.doubleSpinBox_frequency.setProperty("value", 10.0)
        self.doubleSpinBox_frequency.setObjectName("doubleSpinBox_frequency")
        self.dial_mounting_roll = QtWidgets.QDial(self.centralwidget)
        self.dial_mounting_roll.setGeometry(QtCore.QRect(340, 290, 100, 100))
        self.dial_mounting_roll.setMinimum(-1800)
        self.dial_mounting_roll.setMaximum(1800)
        self.dial_mounting_roll.setObjectName("dial_mounting_roll")
        self.doubleSpinBox_mounting_z = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_mounting_z.setGeometry(QtCore.QRect(390, 190, 80, 25))
        self.doubleSpinBox_mounting_z.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_mounting_z.setMinimum(-10.0)
        self.doubleSpinBox_mounting_z.setMaximum(10.0)
        self.doubleSpinBox_mounting_z.setSingleStep(0.1)
        self.doubleSpinBox_mounting_z.setObjectName("doubleSpinBox_mounting_z")
        self.doubleSpinBox_mounting_roll = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_mounting_roll.setGeometry(QtCore.QRect(350, 265, 80, 25))
        self.doubleSpinBox_mounting_roll.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_mounting_roll.setMinimum(-180.0)
        self.doubleSpinBox_mounting_roll.setMaximum(180.0)
        self.doubleSpinBox_mounting_roll.setSingleStep(0.1)
        self.doubleSpinBox_mounting_roll.setObjectName("doubleSpinBox_mounting_roll")
        self.doubleSpinBox_mounting_pitch = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_mounting_pitch.setGeometry(QtCore.QRect(490, 265, 80, 25))
        self.doubleSpinBox_mounting_pitch.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_mounting_pitch.setMinimum(-180.0)
        self.doubleSpinBox_mounting_pitch.setMaximum(180.0)
        self.doubleSpinBox_mounting_pitch.setSingleStep(0.1)
        self.doubleSpinBox_mounting_pitch.setObjectName("doubleSpinBox_mounting_pitch")
        self.doubleSpinBox_mounting_yaw = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_mounting_yaw.setGeometry(QtCore.QRect(620, 265, 80, 25))
        self.doubleSpinBox_mounting_yaw.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_mounting_yaw.setMinimum(-180.0)
        self.doubleSpinBox_mounting_yaw.setMaximum(180.0)
        self.doubleSpinBox_mounting_yaw.setSingleStep(0.1)
        self.doubleSpinBox_mounting_yaw.setObjectName("doubleSpinBox_mounting_yaw")
        self.dial_mounting_pitch = QtWidgets.QDial(self.centralwidget)
        self.dial_mounting_pitch.setGeometry(QtCore.QRect(480, 290, 100, 100))
        self.dial_mounting_pitch.setMinimum(-1800)
        self.dial_mounting_pitch.setMaximum(1800)
        self.dial_mounting_pitch.setObjectName("dial_mounting_pitch")
        self.dial_mounting_yaw = QtWidgets.QDial(self.centralwidget)
        self.dial_mounting_yaw.setGeometry(QtCore.QRect(610, 290, 100, 100))
        self.dial_mounting_yaw.setMinimum(-1800)
        self.dial_mounting_yaw.setMaximum(1800)
        self.dial_mounting_yaw.setObjectName("dial_mounting_yaw")
        self.label_mounting_position = QtWidgets.QLabel(self.centralwidget)
        self.label_mounting_position.setGeometry(QtCore.QRect(340, 100, 150, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_mounting_position.sizePolicy().hasHeightForWidth())
        self.label_mounting_position.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_mounting_position.setFont(font)
        self.label_mounting_position.setAlignment(QtCore.Qt.AlignCenter)
        self.label_mounting_position.setObjectName("label_mounting_position")
        self.horizontalSlider_mounting_x = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_mounting_x.setGeometry(QtCore.QRect(480, 135, 250, 15))
        self.horizontalSlider_mounting_x.setMinimum(-10000)
        self.horizontalSlider_mounting_x.setMaximum(10000)
        self.horizontalSlider_mounting_x.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_mounting_x.setObjectName("horizontalSlider_mounting_x")
        self.horizontalSlider_mounting_y = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_mounting_y.setGeometry(QtCore.QRect(480, 165, 250, 15))
        self.horizontalSlider_mounting_y.setMinimum(-10000)
        self.horizontalSlider_mounting_y.setMaximum(10000)
        self.horizontalSlider_mounting_y.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_mounting_y.setObjectName("horizontalSlider_mounting_y")
        self.horizontalSlider_mounting_z = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_mounting_z.setGeometry(QtCore.QRect(480, 195, 250, 15))
        self.horizontalSlider_mounting_z.setMinimum(-10000)
        self.horizontalSlider_mounting_z.setMaximum(10000)
        self.horizontalSlider_mounting_z.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_mounting_z.setObjectName("horizontalSlider_mounting_z")
        self.mounting_parameter = QtWidgets.QLabel(self.centralwidget)
        self.mounting_parameter.setGeometry(QtCore.QRect(330, 30, 220, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mounting_parameter.sizePolicy().hasHeightForWidth())
        self.mounting_parameter.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.mounting_parameter.setFont(font)
        self.mounting_parameter.setAlignment(QtCore.Qt.AlignCenter)
        self.mounting_parameter.setObjectName("mounting_parameter")
        self.mounting_posture = QtWidgets.QLabel(self.centralwidget)
        self.mounting_posture.setGeometry(QtCore.QRect(340, 220, 150, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mounting_posture.sizePolicy().hasHeightForWidth())
        self.mounting_posture.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.mounting_posture.setFont(font)
        self.mounting_posture.setAlignment(QtCore.Qt.AlignCenter)
        self.mounting_posture.setObjectName("mounting_posture")
        self.label_spec = QtWidgets.QLabel(self.centralwidget)
        self.label_spec.setGeometry(QtCore.QRect(20, 100, 220, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_spec.sizePolicy().hasHeightForWidth())
        self.label_spec.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_spec.setFont(font)
        self.label_spec.setAlignment(QtCore.Qt.AlignCenter)
        self.label_spec.setObjectName("label_spec")
        self.label_name = QtWidgets.QLabel(self.centralwidget)
        self.label_name.setGeometry(QtCore.QRect(16, 30, 120, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_name.sizePolicy().hasHeightForWidth())
        self.label_name.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_name.setFont(font)
        self.label_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name.setObjectName("label_name")
        self.label_parent_frame = QtWidgets.QLabel(self.centralwidget)
        self.label_parent_frame.setGeometry(QtCore.QRect(340, 65, 130, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_parent_frame.sizePolicy().hasHeightForWidth())
        self.label_parent_frame.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_parent_frame.setFont(font)
        self.label_parent_frame.setAlignment(QtCore.Qt.AlignCenter)
        self.label_parent_frame.setObjectName("label_parent_frame")
        self.doubleSpinBox_color_r = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_color_r.setGeometry(QtCore.QRect(60, 415, 70, 27))
        self.doubleSpinBox_color_r.setDecimals(3)
        self.doubleSpinBox_color_r.setMaximum(1.0)
        self.doubleSpinBox_color_r.setSingleStep(0.001)
        self.doubleSpinBox_color_r.setObjectName("doubleSpinBox_color_r")
        self.label_name_color_g = QtWidgets.QLabel(self.centralwidget)
        self.label_name_color_g.setGeometry(QtCore.QRect(190, 420, 15, 18))
        self.label_name_color_g.setObjectName("label_name_color_g")
        self.doubleSpinBox_color_g = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_color_g.setGeometry(QtCore.QRect(210, 415, 70, 27))
        self.doubleSpinBox_color_g.setDecimals(3)
        self.doubleSpinBox_color_g.setMaximum(1.0)
        self.doubleSpinBox_color_g.setSingleStep(0.001)
        self.doubleSpinBox_color_g.setObjectName("doubleSpinBox_color_g")
        self.doubleSpinBox_color_b = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_color_b.setGeometry(QtCore.QRect(360, 415, 70, 27))
        self.doubleSpinBox_color_b.setDecimals(3)
        self.doubleSpinBox_color_b.setMaximum(1.0)
        self.doubleSpinBox_color_b.setSingleStep(0.001)
        self.doubleSpinBox_color_b.setObjectName("doubleSpinBox_color_b")
        self.label_name_color_r = QtWidgets.QLabel(self.centralwidget)
        self.label_name_color_r.setGeometry(QtCore.QRect(40, 420, 15, 18))
        self.label_name_color_r.setObjectName("label_name_color_r")
        self.doubleSpinBox_color_a = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_color_a.setGeometry(QtCore.QRect(500, 415, 70, 27))
        self.doubleSpinBox_color_a.setDecimals(3)
        self.doubleSpinBox_color_a.setMaximum(1.0)
        self.doubleSpinBox_color_a.setSingleStep(0.001)
        self.doubleSpinBox_color_a.setObjectName("doubleSpinBox_color_a")
        self.label_name_color_a = QtWidgets.QLabel(self.centralwidget)
        self.label_name_color_a.setGeometry(QtCore.QRect(480, 420, 15, 18))
        self.label_name_color_a.setObjectName("label_name_color_a")
        self.label_name_color_b = QtWidgets.QLabel(self.centralwidget)
        self.label_name_color_b.setGeometry(QtCore.QRect(340, 420, 15, 18))
        self.label_name_color_b.setObjectName("label_name_color_b")
        self.label_color = QtWidgets.QLabel(self.centralwidget)
        self.label_color.setGeometry(QtCore.QRect(0, 380, 120, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_color.sizePolicy().hasHeightForWidth())
        self.label_color.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_color.setFont(font)
        self.label_color.setAlignment(QtCore.Qt.AlignCenter)
        self.label_color.setObjectName("label_color")
        self.menubar = QtWidgets.QMenuBar(LidarForm)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 754, 23))
        self.menubar.setObjectName("menubar")
        self.statusbar = QtWidgets.QStatusBar(LidarForm)
        self.statusbar.setGeometry(QtCore.QRect(0, 0, 3, 23))
        self.statusbar.setObjectName("statusbar")

        self.retranslateUi(LidarForm)
        self.pushButton.pressed.connect(LidarForm.change_param)
        self.dial_mounting_roll.sliderMoved['int'].connect(LidarForm.update_spinbox_pos)
        self.dial_mounting_pitch.sliderMoved['int'].connect(LidarForm.update_spinbox_pos)
        self.dial_mounting_roll.sliderPressed.connect(LidarForm.update_spinbox_pos)
        self.dial_mounting_roll.sliderReleased.connect(LidarForm.update_spinbox_pos)
        self.dial_mounting_pitch.sliderPressed.connect(LidarForm.update_spinbox_pos)
        self.dial_mounting_yaw.sliderMoved['int'].connect(LidarForm.update_spinbox_pos)
        self.dial_mounting_pitch.sliderReleased.connect(LidarForm.update_spinbox_pos)
        self.dial_mounting_yaw.sliderPressed.connect(LidarForm.update_spinbox_pos)
        self.dial_mounting_yaw.sliderReleased.connect(LidarForm.update_spinbox_pos)
        self.horizontalSlider_mounting_x.sliderMoved['int'].connect(LidarForm.update_spinbox_pos)
        self.horizontalSlider_mounting_x.sliderPressed.connect(LidarForm.update_spinbox_pos)
        self.horizontalSlider_mounting_x.sliderReleased.connect(LidarForm.update_spinbox_pos)
        self.horizontalSlider_mounting_y.sliderMoved['int'].connect(LidarForm.update_spinbox_pos)
        self.horizontalSlider_mounting_y.sliderPressed.connect(LidarForm.update_spinbox_pos)
        self.horizontalSlider_mounting_z.sliderMoved['int'].connect(LidarForm.update_spinbox_pos)
        self.horizontalSlider_mounting_y.sliderReleased.connect(LidarForm.update_spinbox_pos)
        self.horizontalSlider_mounting_z.sliderPressed.connect(LidarForm.update_spinbox_pos)
        self.horizontalSlider_mounting_z.sliderReleased.connect(LidarForm.update_spinbox_pos)
        self.doubleSpinBox_mounting_z.valueChanged['double'].connect(LidarForm.update_slider_pos)
        self.doubleSpinBox_mounting_y.valueChanged['double'].connect(LidarForm.update_slider_pos)
        self.doubleSpinBox_mounting_roll.valueChanged['double'].connect(LidarForm.update_dial_pos)
        self.doubleSpinBox_mounting_pitch.valueChanged['double'].connect(LidarForm.update_dial_pos)
        self.doubleSpinBox_mounting_yaw.valueChanged['double'].connect(LidarForm.update_dial_pos)
        self.doubleSpinBox_mounting_x.valueChanged['double'].connect(LidarForm.update_slider_pos)
        QtCore.QMetaObject.connectSlotsByName(LidarForm)

    def retranslateUi(self, LidarForm):
        _translate = QtCore.QCoreApplication.translate
        LidarForm.setWindowTitle(_translate("LidarForm", "___"))
        self.pushButton.setText(_translate("LidarForm", "change parameter"))
        self.label_horizontal_fov.setText(_translate("LidarForm", "horizontal fov [deg]"))
        self.label_vertical_fov.setText(_translate("LidarForm", "vertical fov [deg]"))
        self.label_horizontal_resolution.setText(_translate("LidarForm", "horzontal resolution [deg]"))
        self.label_vertical_resolution.setText(_translate("LidarForm", "vertical resolution [deg]"))
        self.label_max_range.setText(_translate("LidarForm", "max detection range [m]"))
        self.label_min_range.setText(_translate("LidarForm", "min detection range [m]"))
        self.label_mounting_x.setText(_translate("LidarForm", " x [m]"))
        self.label_mounting_y.setText(_translate("LidarForm", " y [m]"))
        self.label_mounting_z.setText(_translate("LidarForm", " z [m]"))
        self.label_mounting_roll.setText(_translate("LidarForm", " roll [deg]"))
        self.label_mounting_pitch.setText(_translate("LidarForm", "pitch [deg]"))
        self.label_mounting_yaw.setText(_translate("LidarForm", " yaw [deg]"))
        self.label_frequency.setText(_translate("LidarForm", "update frequency [Hz]"))
        self.label_mounting_position.setText(_translate("LidarForm", "mounting ptiotion"))
        self.mounting_parameter.setText(_translate("LidarForm", "mounting paremeters"))
        self.mounting_posture.setText(_translate("LidarForm", "mounting posture"))
        self.label_spec.setText(_translate("LidarForm", "detection specifications"))
        self.label_name.setText(_translate("LidarForm", "sensor name"))
        self.label_parent_frame.setText(_translate("LidarForm", "parent frame id"))
        self.label_name_color_g.setText(_translate("LidarForm", "G"))
        self.label_name_color_r.setText(_translate("LidarForm", "R"))
        self.label_name_color_a.setText(_translate("LidarForm", "A"))
        self.label_name_color_b.setText(_translate("LidarForm", "B"))
        self.label_color.setText(_translate("LidarForm", "color"))
