# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sensor_sim_ui_object_form.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ObjectForm(object):
    def setupUi(self, ObjectForm):
        ObjectForm.setObjectName("ObjectForm")
        ObjectForm.resize(600, 400)
        self.label_length = QtWidgets.QLabel(ObjectForm)
        self.label_length.setGeometry(QtCore.QRect(20, 95, 70, 18))
        self.label_length.setObjectName("label_length")
        self.label_width = QtWidgets.QLabel(ObjectForm)
        self.label_width.setGeometry(QtCore.QRect(20, 185, 70, 18))
        self.label_width.setObjectName("label_width")
        self.label_height = QtWidgets.QLabel(ObjectForm)
        self.label_height.setGeometry(QtCore.QRect(20, 275, 70, 18))
        self.label_height.setObjectName("label_height")
        self.label_pos_x = QtWidgets.QLabel(ObjectForm)
        self.label_pos_x.setGeometry(QtCore.QRect(230, 95, 70, 18))
        self.label_pos_x.setObjectName("label_pos_x")
        self.label_pos_y = QtWidgets.QLabel(ObjectForm)
        self.label_pos_y.setGeometry(QtCore.QRect(230, 185, 70, 18))
        self.label_pos_y.setObjectName("label_pos_y")
        self.label_pos_z = QtWidgets.QLabel(ObjectForm)
        self.label_pos_z.setGeometry(QtCore.QRect(230, 275, 70, 18))
        self.label_pos_z.setObjectName("label_pos_z")
        self.label_roll = QtWidgets.QLabel(ObjectForm)
        self.label_roll.setGeometry(QtCore.QRect(440, 95, 55, 18))
        self.label_roll.setObjectName("label_roll")
        self.label_pitch = QtWidgets.QLabel(ObjectForm)
        self.label_pitch.setGeometry(QtCore.QRect(440, 185, 70, 18))
        self.label_pitch.setObjectName("label_pitch")
        self.label_yaw = QtWidgets.QLabel(ObjectForm)
        self.label_yaw.setGeometry(QtCore.QRect(440, 275, 70, 18))
        self.label_yaw.setObjectName("label_yaw")
        self.doubleSpinBox_length = QtWidgets.QDoubleSpinBox(ObjectForm)
        self.doubleSpinBox_length.setGeometry(QtCore.QRect(110, 95, 70, 27))
        self.doubleSpinBox_length.setDecimals(3)
        self.doubleSpinBox_length.setMaximum(1000.0)
        self.doubleSpinBox_length.setSingleStep(0.001)
        self.doubleSpinBox_length.setObjectName("doubleSpinBox_length")
        self.doubleSpinBox_width = QtWidgets.QDoubleSpinBox(ObjectForm)
        self.doubleSpinBox_width.setGeometry(QtCore.QRect(110, 185, 70, 27))
        self.doubleSpinBox_width.setDecimals(3)
        self.doubleSpinBox_width.setMaximum(1000.0)
        self.doubleSpinBox_width.setSingleStep(0.001)
        self.doubleSpinBox_width.setObjectName("doubleSpinBox_width")
        self.doubleSpinBox_height = QtWidgets.QDoubleSpinBox(ObjectForm)
        self.doubleSpinBox_height.setGeometry(QtCore.QRect(110, 275, 70, 27))
        self.doubleSpinBox_height.setDecimals(3)
        self.doubleSpinBox_height.setMaximum(1000.0)
        self.doubleSpinBox_height.setSingleStep(0.001)
        self.doubleSpinBox_height.setObjectName("doubleSpinBox_height")
        self.doubleSpinBox_pos_x = QtWidgets.QDoubleSpinBox(ObjectForm)
        self.doubleSpinBox_pos_x.setGeometry(QtCore.QRect(320, 95, 70, 27))
        self.doubleSpinBox_pos_x.setDecimals(3)
        self.doubleSpinBox_pos_x.setMinimum(-1000.0)
        self.doubleSpinBox_pos_x.setMaximum(1000.0)
        self.doubleSpinBox_pos_x.setSingleStep(0.001)
        self.doubleSpinBox_pos_x.setObjectName("doubleSpinBox_pos_x")
        self.doubleSpinBox_pos_y = QtWidgets.QDoubleSpinBox(ObjectForm)
        self.doubleSpinBox_pos_y.setGeometry(QtCore.QRect(320, 185, 70, 27))
        self.doubleSpinBox_pos_y.setDecimals(3)
        self.doubleSpinBox_pos_y.setMinimum(-1000.0)
        self.doubleSpinBox_pos_y.setMaximum(1000.0)
        self.doubleSpinBox_pos_y.setSingleStep(0.001)
        self.doubleSpinBox_pos_y.setObjectName("doubleSpinBox_pos_y")
        self.doubleSpinBox_pos_z = QtWidgets.QDoubleSpinBox(ObjectForm)
        self.doubleSpinBox_pos_z.setGeometry(QtCore.QRect(320, 275, 70, 27))
        self.doubleSpinBox_pos_z.setDecimals(3)
        self.doubleSpinBox_pos_z.setMinimum(-1000.0)
        self.doubleSpinBox_pos_z.setMaximum(1000.0)
        self.doubleSpinBox_pos_z.setSingleStep(0.001)
        self.doubleSpinBox_pos_z.setObjectName("doubleSpinBox_pos_z")
        self.doubleSpinBox_roll = QtWidgets.QDoubleSpinBox(ObjectForm)
        self.doubleSpinBox_roll.setGeometry(QtCore.QRect(440, 120, 62, 27))
        self.doubleSpinBox_roll.setDecimals(3)
        self.doubleSpinBox_roll.setMinimum(-180.0)
        self.doubleSpinBox_roll.setMaximum(180.0)
        self.doubleSpinBox_roll.setSingleStep(0.01)
        self.doubleSpinBox_roll.setObjectName("doubleSpinBox_roll")
        self.doubleSpinBox_pitch = QtWidgets.QDoubleSpinBox(ObjectForm)
        self.doubleSpinBox_pitch.setGeometry(QtCore.QRect(440, 210, 62, 27))
        self.doubleSpinBox_pitch.setDecimals(3)
        self.doubleSpinBox_pitch.setMinimum(-180.0)
        self.doubleSpinBox_pitch.setMaximum(180.0)
        self.doubleSpinBox_pitch.setSingleStep(0.01)
        self.doubleSpinBox_pitch.setObjectName("doubleSpinBox_pitch")
        self.doubleSpinBox_yaw = QtWidgets.QDoubleSpinBox(ObjectForm)
        self.doubleSpinBox_yaw.setGeometry(QtCore.QRect(440, 300, 62, 27))
        self.doubleSpinBox_yaw.setDecimals(3)
        self.doubleSpinBox_yaw.setMinimum(-180.0)
        self.doubleSpinBox_yaw.setMaximum(180.0)
        self.doubleSpinBox_yaw.setSingleStep(0.01)
        self.doubleSpinBox_yaw.setObjectName("doubleSpinBox_yaw")
        self.horizontalSlider_length = QtWidgets.QSlider(ObjectForm)
        self.horizontalSlider_length.setGeometry(QtCore.QRect(20, 125, 160, 16))
        self.horizontalSlider_length.setMaximum(1000000)
        self.horizontalSlider_length.setSingleStep(1)
        self.horizontalSlider_length.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_length.setObjectName("horizontalSlider_length")
        self.horizontalSlider_width = QtWidgets.QSlider(ObjectForm)
        self.horizontalSlider_width.setGeometry(QtCore.QRect(20, 215, 160, 16))
        self.horizontalSlider_width.setMaximum(1000000)
        self.horizontalSlider_width.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_width.setObjectName("horizontalSlider_width")
        self.horizontalSlider_height = QtWidgets.QSlider(ObjectForm)
        self.horizontalSlider_height.setGeometry(QtCore.QRect(20, 305, 160, 16))
        self.horizontalSlider_height.setMaximum(1000000)
        self.horizontalSlider_height.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_height.setObjectName("horizontalSlider_height")
        self.pushButton = QtWidgets.QPushButton(ObjectForm)
        self.pushButton.setGeometry(QtCore.QRect(70, 350, 460, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalSlider_pos_x = QtWidgets.QSlider(ObjectForm)
        self.horizontalSlider_pos_x.setGeometry(QtCore.QRect(230, 125, 160, 16))
        self.horizontalSlider_pos_x.setMinimum(-1000000)
        self.horizontalSlider_pos_x.setMaximum(1000000)
        self.horizontalSlider_pos_x.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_pos_x.setObjectName("horizontalSlider_pos_x")
        self.horizontalSlider_pos_y = QtWidgets.QSlider(ObjectForm)
        self.horizontalSlider_pos_y.setGeometry(QtCore.QRect(230, 215, 160, 16))
        self.horizontalSlider_pos_y.setMinimum(-1000000)
        self.horizontalSlider_pos_y.setMaximum(1000000)
        self.horizontalSlider_pos_y.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_pos_y.setObjectName("horizontalSlider_pos_y")
        self.horizontalSlider_pos_z = QtWidgets.QSlider(ObjectForm)
        self.horizontalSlider_pos_z.setGeometry(QtCore.QRect(230, 305, 160, 16))
        self.horizontalSlider_pos_z.setMinimum(-1000000)
        self.horizontalSlider_pos_z.setMaximum(1000000)
        self.horizontalSlider_pos_z.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_pos_z.setObjectName("horizontalSlider_pos_z")
        self.dial_roll = QtWidgets.QDial(ObjectForm)
        self.dial_roll.setGeometry(QtCore.QRect(500, 85, 81, 81))
        self.dial_roll.setMinimum(-18000)
        self.dial_roll.setMaximum(18000)
        self.dial_roll.setObjectName("dial_roll")
        self.dial_pitch = QtWidgets.QDial(ObjectForm)
        self.dial_pitch.setGeometry(QtCore.QRect(500, 175, 81, 81))
        self.dial_pitch.setMinimum(-18000)
        self.dial_pitch.setMaximum(18000)
        self.dial_pitch.setObjectName("dial_pitch")
        self.dial_yaw = QtWidgets.QDial(ObjectForm)
        self.dial_yaw.setGeometry(QtCore.QRect(500, 265, 81, 81))
        self.dial_yaw.setMinimum(-18000)
        self.dial_yaw.setMaximum(18000)
        self.dial_yaw.setObjectName("dial_yaw")
        self.lineEdit_name = QtWidgets.QLineEdit(ObjectForm)
        self.lineEdit_name.setGeometry(QtCore.QRect(60, 10, 120, 26))
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.label_name = QtWidgets.QLabel(ObjectForm)
        self.label_name.setGeometry(QtCore.QRect(20, 15, 55, 18))
        self.label_name.setObjectName("label_name")
        self.label_parent_frame_id = QtWidgets.QLabel(ObjectForm)
        self.label_parent_frame_id.setGeometry(QtCore.QRect(210, 15, 90, 18))
        self.label_parent_frame_id.setObjectName("label_parent_frame_id")
        self.lineEdit_frame = QtWidgets.QLineEdit(ObjectForm)
        self.lineEdit_frame.setGeometry(QtCore.QRect(310, 10, 113, 26))
        self.lineEdit_frame.setObjectName("lineEdit_frame")
        self.label_name_color_r = QtWidgets.QLabel(ObjectForm)
        self.label_name_color_r.setGeometry(QtCore.QRect(20, 55, 15, 18))
        self.label_name_color_r.setObjectName("label_name_color_r")
        self.doubleSpinBox_color_r = QtWidgets.QDoubleSpinBox(ObjectForm)
        self.doubleSpinBox_color_r.setGeometry(QtCore.QRect(40, 50, 70, 27))
        self.doubleSpinBox_color_r.setDecimals(3)
        self.doubleSpinBox_color_r.setMaximum(1.0)
        self.doubleSpinBox_color_r.setSingleStep(0.001)
        self.doubleSpinBox_color_r.setObjectName("doubleSpinBox_color_r")
        self.doubleSpinBox_color_g = QtWidgets.QDoubleSpinBox(ObjectForm)
        self.doubleSpinBox_color_g.setGeometry(QtCore.QRect(190, 50, 70, 27))
        self.doubleSpinBox_color_g.setDecimals(3)
        self.doubleSpinBox_color_g.setMaximum(1.0)
        self.doubleSpinBox_color_g.setSingleStep(0.001)
        self.doubleSpinBox_color_g.setObjectName("doubleSpinBox_color_g")
        self.label_name_color_g = QtWidgets.QLabel(ObjectForm)
        self.label_name_color_g.setGeometry(QtCore.QRect(170, 55, 15, 18))
        self.label_name_color_g.setObjectName("label_name_color_g")
        self.label_name_color_b = QtWidgets.QLabel(ObjectForm)
        self.label_name_color_b.setGeometry(QtCore.QRect(320, 55, 15, 18))
        self.label_name_color_b.setObjectName("label_name_color_b")
        self.doubleSpinBox_color_b = QtWidgets.QDoubleSpinBox(ObjectForm)
        self.doubleSpinBox_color_b.setGeometry(QtCore.QRect(340, 50, 70, 27))
        self.doubleSpinBox_color_b.setDecimals(3)
        self.doubleSpinBox_color_b.setMaximum(1.0)
        self.doubleSpinBox_color_b.setSingleStep(0.001)
        self.doubleSpinBox_color_b.setObjectName("doubleSpinBox_color_b")
        self.doubleSpinBox_color_a = QtWidgets.QDoubleSpinBox(ObjectForm)
        self.doubleSpinBox_color_a.setGeometry(QtCore.QRect(480, 50, 70, 27))
        self.doubleSpinBox_color_a.setDecimals(3)
        self.doubleSpinBox_color_a.setMaximum(1.0)
        self.doubleSpinBox_color_a.setSingleStep(0.001)
        self.doubleSpinBox_color_a.setObjectName("doubleSpinBox_color_a")
        self.label_name_color_a = QtWidgets.QLabel(ObjectForm)
        self.label_name_color_a.setGeometry(QtCore.QRect(460, 55, 15, 18))
        self.label_name_color_a.setObjectName("label_name_color_a")

        self.retranslateUi(ObjectForm)
        self.horizontalSlider_length.valueChanged['int'].connect(ObjectForm.update_spinbox_pos)
        self.horizontalSlider_width.valueChanged['int'].connect(ObjectForm.update_spinbox_pos)
        self.horizontalSlider_height.valueChanged['int'].connect(ObjectForm.update_spinbox_pos)
        self.horizontalSlider_length.sliderMoved['int'].connect(ObjectForm.update_spinbox_pos)
        self.horizontalSlider_width.sliderMoved['int'].connect(ObjectForm.update_spinbox_pos)
        self.horizontalSlider_height.sliderMoved['int'].connect(ObjectForm.update_spinbox_pos)
        self.pushButton.pressed.connect(ObjectForm.change_param)
        self.doubleSpinBox_length.valueChanged['double'].connect(ObjectForm.update_slider_pos)
        self.doubleSpinBox_width.valueChanged['double'].connect(ObjectForm.update_slider_pos)
        self.doubleSpinBox_height.valueChanged['double'].connect(ObjectForm.update_slider_pos)
        self.horizontalSlider_pos_x.sliderMoved['int'].connect(ObjectForm.update_spinbox_pos)
        self.horizontalSlider_pos_x.valueChanged['int'].connect(ObjectForm.update_spinbox_pos)
        self.doubleSpinBox_pos_y.valueChanged['double'].connect(ObjectForm.update_slider_pos)
        self.horizontalSlider_pos_y.sliderMoved['int'].connect(ObjectForm.update_spinbox_pos)
        self.horizontalSlider_pos_y.sliderPressed.connect(ObjectForm.update_spinbox_pos)
        self.horizontalSlider_pos_z.sliderPressed.connect(ObjectForm.update_spinbox_pos)
        self.horizontalSlider_pos_z.sliderMoved['int'].connect(ObjectForm.update_spinbox_pos)
        self.doubleSpinBox_pos_x.valueChanged['double'].connect(ObjectForm.update_slider_pos)
        self.doubleSpinBox_pos_z.valueChanged['double'].connect(ObjectForm.update_slider_pos)
        self.doubleSpinBox_roll.valueChanged['double'].connect(ObjectForm.update_dial_pos)
        self.doubleSpinBox_pitch.valueChanged['double'].connect(ObjectForm.update_dial_pos)
        self.doubleSpinBox_yaw.valueChanged['double'].connect(ObjectForm.update_dial_pos)
        self.dial_roll.sliderMoved['int'].connect(ObjectForm.update_spinbox_pos)
        self.dial_roll.valueChanged['int'].connect(ObjectForm.update_spinbox_pos)
        self.dial_pitch.sliderMoved['int'].connect(ObjectForm.update_spinbox_pos)
        self.dial_pitch.valueChanged['int'].connect(ObjectForm.update_spinbox_pos)
        self.dial_yaw.sliderMoved['int'].connect(ObjectForm.update_spinbox_pos)
        self.dial_yaw.valueChanged['int'].connect(ObjectForm.update_spinbox_pos)
        QtCore.QMetaObject.connectSlotsByName(ObjectForm)

    def retranslateUi(self, ObjectForm):
        _translate = QtCore.QCoreApplication.translate
        ObjectForm.setWindowTitle(_translate("ObjectForm", "Form"))
        self.label_length.setText(_translate("ObjectForm", "length [m]"))
        self.label_width.setText(_translate("ObjectForm", "width [m]"))
        self.label_height.setText(_translate("ObjectForm", "height [m]"))
        self.label_pos_x.setText(_translate("ObjectForm", "Center x [m]"))
        self.label_pos_y.setText(_translate("ObjectForm", "Center y [m]"))
        self.label_pos_z.setText(_translate("ObjectForm", "Center z [m]"))
        self.label_roll.setText(_translate("ObjectForm", "roll [deg]"))
        self.label_pitch.setText(_translate("ObjectForm", "pitch [deg]"))
        self.label_yaw.setText(_translate("ObjectForm", "yaw [deg]"))
        self.pushButton.setText(_translate("ObjectForm", "change parameter"))
        self.label_name.setText(_translate("ObjectForm", "name"))
        self.label_parent_frame_id.setText(_translate("ObjectForm", "parent frame id"))
        self.label_name_color_r.setText(_translate("ObjectForm", "R"))
        self.label_name_color_g.setText(_translate("ObjectForm", "G"))
        self.label_name_color_b.setText(_translate("ObjectForm", "B"))
        self.label_name_color_a.setText(_translate("ObjectForm", "A"))
