# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sensor_sim_ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(584, 218)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_lidar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_lidar.setGeometry(QtCore.QRect(20, 40, 80, 26))
        self.pushButton_lidar.setObjectName("pushButton_lidar")
        self.lineEdit_lidar_name = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_lidar_name.setGeometry(QtCore.QRect(235, 40, 120, 26))
        self.lineEdit_lidar_name.setObjectName("lineEdit_lidar_name")
        self.spinBox_lidar = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_lidar.setGeometry(QtCore.QRect(120, 40, 44, 27))
        self.spinBox_lidar.setMaximum(100)
        self.spinBox_lidar.setObjectName("spinBox_lidar")
        self.label_lidar = QtWidgets.QLabel(self.centralwidget)
        self.label_lidar.setGeometry(QtCore.QRect(10, 10, 60, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_lidar.setFont(font)
        self.label_lidar.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_lidar.setObjectName("label_lidar")
        self.label_object = QtWidgets.QLabel(self.centralwidget)
        self.label_object.setGeometry(QtCore.QRect(10, 100, 60, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_object.setFont(font)
        self.label_object.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_object.setObjectName("label_object")
        self.lineEdit_object_name = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_object_name.setGeometry(QtCore.QRect(235, 130, 120, 26))
        self.lineEdit_object_name.setObjectName("lineEdit_object_name")
        self.spinBox_object = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_object.setGeometry(QtCore.QRect(120, 130, 44, 27))
        self.spinBox_object.setMaximum(100)
        self.spinBox_object.setObjectName("spinBox_object")
        self.pushButton_object = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_object.setGeometry(QtCore.QRect(20, 130, 80, 26))
        self.pushButton_object.setObjectName("pushButton_object")
        self.lineEdit_lidar_frame = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_lidar_frame.setGeometry(QtCore.QRect(440, 40, 120, 26))
        self.lineEdit_lidar_frame.setObjectName("lineEdit_lidar_frame")
        self.lineEdit_object_frame = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_object_frame.setGeometry(QtCore.QRect(440, 130, 120, 26))
        self.lineEdit_object_frame.setObjectName("lineEdit_object_frame")
        self.label_lidar_name = QtWidgets.QLabel(self.centralwidget)
        self.label_lidar_name.setGeometry(QtCore.QRect(180, 40, 50, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_lidar_name.setFont(font)
        self.label_lidar_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_lidar_name.setObjectName("label_lidar_name")
        self.label_object_name = QtWidgets.QLabel(self.centralwidget)
        self.label_object_name.setGeometry(QtCore.QRect(180, 130, 50, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_object_name.setFont(font)
        self.label_object_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_object_name.setObjectName("label_object_name")
        self.label_lidar_frame = QtWidgets.QLabel(self.centralwidget)
        self.label_lidar_frame.setGeometry(QtCore.QRect(380, 40, 60, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_lidar_frame.setFont(font)
        self.label_lidar_frame.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_lidar_frame.setObjectName("label_lidar_frame")
        self.label_object_frame = QtWidgets.QLabel(self.centralwidget)
        self.label_object_frame.setGeometry(QtCore.QRect(380, 130, 60, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_object_frame.setFont(font)
        self.label_object_frame.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_object_frame.setObjectName("label_object_frame")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 584, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_lidar.pressed.connect(MainWindow.add_lidar)
        self.pushButton_object.pressed.connect(MainWindow.add_object)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_lidar.setText(_translate("MainWindow", "add lidar"))
        self.label_lidar.setText(_translate("MainWindow", "Lidar"))
        self.label_object.setText(_translate("MainWindow", "Object"))
        self.pushButton_object.setText(_translate("MainWindow", "add object"))
        self.label_lidar_name.setText(_translate("MainWindow", "name: "))
        self.label_object_name.setText(_translate("MainWindow", "name: "))
        self.label_lidar_frame.setText(_translate("MainWindow", "parent: "))
        self.label_object_frame.setText(_translate("MainWindow", "parent: "))
